'use strict';const test=require('node:test'),assert=require('node:assert/strict'),W=require('../src/domain/travelWorkflow');const{readiness,requireProviders}=require('../src/services/providerBoundary');const hash=c=>c.repeat(64);
function preferences(overrides={}){return{version:'v1',homeCurrency:'USD',startDate:'2026-08-01',endDate:'2026-08-05',budgetMinor:100000,ageGroup:'adult',interests:['art','food'],dietaryNeeds:['vegetarian'],mobilityNeeds:['step_free'],safetyConstraints:['daytime_only'],pace:'balanced',privacyMode:'minimal',...overrides};}
function candidates(){return[{id:'museum',provider:'city-pass',sourceDigest:hash('a'),costMinor:3000,available:true,safetyStatus:'allowed',accessibility:['step_free'],dietary:['vegetarian'],tags:['art'],day:'2026-08-01',startTime:'10:00'},{id:'food-tour',provider:'local-guide',sourceDigest:hash('b'),costMinor:6000,available:true,safetyStatus:'allowed',accessibility:['step_free'],dietary:['vegetarian'],tags:['food'],day:'2026-08-02',startTime:'12:00'},{id:'unsafe',provider:'unknown',sourceDigest:hash('c'),costMinor:1,available:true,safetyStatus:'blocked',accessibility:['step_free'],dietary:['vegetarian'],tags:['art'],day:'2026-08-01',startTime:'01:00'}];}
test('preferences are explicit, minimal, budgeted, and age-sensitive',()=>{const checked=W.validatePreferences(preferences());assert.equal(checked.ok,true);assert.match(checked.preferences.preferencesDigest,/^[a-f0-9]{64}$/);const bad=W.validatePreferences(preferences({ageGroup:'minor_with_guardian',preciseLocationHistory:['x']}));assert.equal(bad.ok,false);assert.match(bad.errors.join(' '),/guardian/);assert.match(bad.errors.join(' '),/precise history/);});
test('recommendations enforce availability, safety, accessibility, diet, budget, diversity, and explanations',()=>{const p=W.validatePreferences(preferences()).preferences,itinerary=W.buildItinerary(p,candidates());assert.equal(itinerary.recommendationCount,2);assert.equal(itinerary.totalCostMinor,9000);assert.equal(itinerary.providerDiversity,2);assert.equal(JSON.stringify(itinerary).includes('unsafe'),false);assert.deepEqual(itinerary.days[0][0].explanation.matchedInterests,['art']);});
test('cold start remains explicit and impossible journeys abstain',()=>{const p=W.validatePreferences(preferences({interests:[]})).preferences,itinerary=W.buildItinerary(p,candidates());assert.equal(itinerary.coldStart,true);const impossible=W.validatePreferences(preferences({budgetMinor:0})).preferences;assert.throws(()=>W.buildItinerary(impossible,candidates()),/no safe accessible/);});
test('edits and feedback create linked corrections without automatic booking',()=>{const itinerary=W.buildItinerary(W.validatePreferences(preferences()).preferences,candidates()),edited=W.editItinerary(itinerary,{actorId:'u1',reason:'museum closed',days:itinerary.days.slice(1),totalCostMinor:6000});assert.equal(edited.parentItineraryDigest,itinerary.itineraryDigest);const feedback=W.feedbackCorrection(edited,{itemId:'museum',reason:'closed',comment:'provider reports closure',preferencePatch:{avoid:['museum']}});assert.equal(feedback.automaticBooking,false);assert.match(feedback.feedbackDigest,/^[a-f0-9]{64}$/);});
test('evaluation covers relevance, diversity, safety, accessibility, cold start, preference changes, failures, and latency',()=>{const itinerary=W.buildItinerary(W.validatePreferences(preferences()).preferences,candidates()),scores={relevance:9000,diversity:9000,safety:10000,accessibility:10000,coldStart:9000,preferenceChange:9000,failureBehavior:10000},passed=W.evaluate(itinerary,{fixtureVersion:'travel-users-v1',evidenceDigest:hash('d'),latencyMs:100,scoresBps:scores});assert.equal(passed.evaluation.passed,true);assert.deepEqual(W.evaluate(itinerary,{fixtureVersion:'v1',evidenceDigest:hash('d'),latencyMs:100,scoresBps:{...scores,accessibility:5000}}).evaluation.failed,['accessibility']);});
test('integrations require consent and least-privilege scopes and reject revocation',()=>{assert.equal(W.integrationConsent({provider:'calendar',consentRef:'consent-1',scopes:['events:read'],grantedAt:'2026-07-01'}).ok,true);const broad=W.integrationConsent({provider:'calendar',consentRef:'c',scopes:['mail:read'],grantedAt:'2026-07-01'});assert.equal(broad.ok,false);const revoked=W.integrationConsent({provider:'calendar',consentRef:'c',scopes:['events:read'],grantedAt:'2026-07-01',revokedAt:'2026-07-02'});assert.match(revoked.errors.join(' '),/revoked/);});
test('booking uses authoritative current quotes and explicit amount approval within budget',()=>{const quoted=W.quote({offerId:'offer-1',provider:'booking-a',searchDigest:hash('a'),currency:'USD',totalMinor:50000,expiresAt:new Date(Date.now()+60000).toISOString(),termsDigest:hash('b'),cancellationPolicy:'free until 24 hours',travelerCount:1}),input={trip:{id:1,state:'approved',budgetMinor:60000,ageGroup:'adult'},quote:quoted,approval:{approvedBy:1,attestationDigest:hash('c'),confirmedTotalMinor:50000,confirmedCurrency:'USD'},providers:['booking_execution']};assert.equal(W.approveBooking(input).ok,true);const over=W.approveBooking({...input,trip:{...input.trip,budgetMinor:40000}});assert.match(over.errors.join(' '),/exceeds/);});
test('deletion propagates to every consented provider and requires receipts',()=>{const plan=W.deletionPlan({subjectId:'u1',requestId:'delete-1',activeProviders:['calendar','booking_search','calendar']});assert.deepEqual(plan.providerDeletions.map(x=>x.provider),['booking_search','calendar']);assert.equal(plan.completed,false);assert.ok(plan.providerDeletions.every(x=>x.receiptRequired));});
test('states and retry limits prevent booking and cancellation shortcuts',()=>{assert.equal(W.transition('review_pending','approved','traveler').ok,true);assert.equal(W.transition('approved','booking_queued','planner').ok,false);assert.equal(W.transition('approved','booking_queued','traveler').ok,true);assert.deepEqual(W.retry(1),{status:'retry',retryable:true,nextDelaySeconds:30});assert.deepEqual(W.retry(5),{status:'dead_letter',retryable:false,nextDelaySeconds:null});});
test('providers and usage fail closed',()=>{assert.equal(readiness({}).ready,false);assert.throws(()=>requireProviders(['booking_execution'],{}),/not ready/);assert.match(W.usage({provider:'maps',operation:'routes',units:2,unitType:'requests',evidenceDigest:hash('e')}).usageDigest,/^[a-f0-9]{64}$/);const env={};for(const name of W.PROVIDERS){const key=name.toUpperCase();env[`${key}_PROVIDER_ENABLED`]='true';env[`${key}_PROVIDER_URL`]=`https://${name}.example.invalid`;env[`${key}_PROVIDER_TOKEN`]='runtime';}assert.equal(readiness(env).ready,true);});
